import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { cn } from "@/lib/utils";
import { ScrollProvider } from "@/components/providers/scroll-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Khám phá Bắc Hà - Kỳ Diệu Vùng Cao Nguyên Trắng",
  description: "Generated by Nevir",
  icons: {
    icon: [
      {
        url: "/favicon.png",
        href: "/favicon.png",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className=" overflow-clip">
      <body className={inter.className}>
        <ScrollProvider>{children}</ScrollProvider>
      </body>
    </html>
  );
}
